# Generated by Django 4.2.2 on 2023-07-16 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0003_wish"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserWish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="wish",
            name="wish_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cart.userwish"
            ),
        ),
    ]
