# Generated by Django 4.2.2 on 2023-07-16 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_userwish_alter_wish_wish_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wish",
            name="product",
        ),
        migrations.RemoveField(
            model_name="wish",
            name="wish_id",
        ),
        migrations.DeleteModel(
            name="UserWish",
        ),
        migrations.DeleteModel(
            name="Wish",
        ),
    ]
