# Generated by Django 4.2.2 on 2023-07-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0007_wallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="Wallettotal",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
