# Generated by Django 4.2.2 on 2023-07-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0006_remove_order_signature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("CANCELLED", "Cancelled"),
                    ("DELIVERED", "Delivered"),
                    ("SHIPPED", "shipped"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
