# Generated by Django 4.2.2 on 2023-07-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0007_alter_order_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("PREPAID", "PREPAID"),
                    ("CASH_ON_DELIVERY", "Cash on Delivery"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("CANCELLED", "Cancelled"),
                    ("DELIVERED", "Delivered"),
                    ("SHIPPED", "shipped"),
                    ("ORDERED", "ordered"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
