# Generated by Django 4.2.2 on 2023-07-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0009_alter_order_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("PREPAID", "PREPAID"),
                    ("CASH_ON_DELIVERY", "Cash on Delivery"),
                    ("WALLET", "wallet"),
                ],
                max_length=20,
            ),
        ),
    ]
