# Generated by Django 4.2.2 on 2023-07-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0010_alter_order_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("CANCELLED", "Cancelled"),
                    ("DELIVERED", "Delivered"),
                    ("SHIPPED", "shipped"),
                    ("ORDERED", "ordered"),
                    ("RETURN", "return"),
                    ("REFUND", "refund"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
