# Generated by Django 4.2.2 on 2023-06-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_remove_products_img_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categ",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
