# Generated by Django 4.2.2 on 2023-07-01 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_categ_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="colour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("colour", models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name="products",
            name="stock",
        ),
        migrations.AlterField(
            model_name="product_image",
            name="image",
            field=models.ImageField(upload_to="products/images"),
        ),
        migrations.CreateModel(
            name="productVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock", models.IntegerField()),
                ("displayimage", models.ImageField(upload_to="product_images")),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "colour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.colour"
                    ),
                ),
                (
                    "products",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.products"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="product_image",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="store.productvariant"
            ),
        ),
    ]
