# Generated by Django 4.2.2 on 2023-07-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_colour_remove_products_stock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="discountprice",
            field=models.IntegerField(default=True, null=True),
        ),
    ]
