# Generated by Django 4.2.2 on 2023-07-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_products_discountprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="categ",
            name="categoryoffer",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
