# Generated by Django 4.2.2 on 2023-07-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_categ_categoryoffer"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarouselBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="carousel_images")),
            ],
        ),
    ]
