# Generated by Django 4.2.2 on 2023-07-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0002_coupon_expiry_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("userwallet", models.IntegerField(default=50)),
                ("referrerdwallet", models.IntegerField(default=100)),
            ],
        ),
    ]
